Pages/Management/AddGame.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using CloudinaryDotNet;
using CloudinaryDotNet.Actions;
using dotenv.net;
using Microsoft.AspNetCore.Hosting;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using EvoltingStore.Entity;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace EvoltingStore.Pages.Management
{
    public class AddGameModel : PageModel
    {
        private EvoltingStoreContext context = new EvoltingStoreContext();

        private readonly Microsoft.AspNetCore.Hosting.IHostingEnvironment _environment;
        public AddGameModel(Microsoft.AspNetCore.Hosting.IHostingEnvironment environment)
        {
            _environment = environment;
        }

        public IActionResult OnGet()
        {

            String userJSON = (String)HttpContext.Session.GetString("user");
            User user = (User)Newtonsoft.Json.JsonConvert.DeserializeObject<User>(userJSON);
            if(user.RoleId == 1)
            {
                List<Genre> allGenres = context.Genres.ToList();

                string jsonGenre = Newtonsoft.Json.JsonConvert.SerializeObject(allGenres);

                ViewData["genres"] = jsonGenre;

                return Page();
            }

            return Redirect("/Error");
        }


        public async Task<IActionResult> OnPost(IFormFile gameImg, Game game, List<int> genres)
        {
            var context = new EvoltingStoreContext();
            List<Genre> allGenres = context.Genres.ToList();

            if (gameImg != null)
            {
                var file = Path.Combine(_environment.ContentRootPath, "uploads", gameImg.FileName);
                using (var fileStream = new FileStream(file, FileMode.Create))
                {
                    await gameImg.CopyToAsync(fileStream);
                }
            }

            DotEnv.Load(options: new DotEnvOptions(probeForEnv: true));
            Cloudinary cloudinary = new Cloudinary(Environment.GetEnvironmentVariable("CLOUDINARY_URL"));
            cloudinary.Api.Secure = true;

            var uploadParams = new ImageUploadParams()
            {
                File = new FileDescription(Path.Combine(_environment.ContentRootPath, "uploads", gameImg.FileName)),
                UseFilename = true,
                UniqueFilename = false,
                Overwrite = true
            };
            var uploadResult = cloudinary.Upload(uploadParams);
            var myJsonString = uploadResult.JsonObj.ToString();
            var data = JObject.Parse(myJsonString);

            var url = data["url"].ToString();

            game.Image = url;
            game.UpdateDate = DateTime.Now;

            foreach(var g in genres)
            {
                game.Genres.Add(allGenres[g-1]);
            }

            context.Games.Add(game);
            context.SaveChanges();

            context = new EvoltingStoreContext();

            return Redirect("/Management/Games");
        }
    }
}

Pages/Management/DeleteGame.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EvoltingStore.Pages.Management
{
    public class DeleteGameModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Management/EditGame.cshtml.cs
using CloudinaryDotNet.Actions;
using CloudinaryDotNet;
using dotenv.net;
using EvoltingStore.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json.Linq;
using Microsoft.EntityFrameworkCore;

namespace EvoltingStore.Pages.Management
{
    public class EditGameModel : PageModel
    {
        private EvoltingStoreContext context = new EvoltingStoreContext();

        private readonly Microsoft.AspNetCore.Hosting.IHostingEnvironment _environment;
        public EditGameModel(Microsoft.AspNetCore.Hosting.IHostingEnvironment environment)
        {
            _environment = environment;
        }

        public IActionResult OnGet(int gameId)
        {
            String userJSON = (String)HttpContext.Session.GetString("user");
            User user = (User)Newtonsoft.Json.JsonConvert.DeserializeObject<User>(userJSON);
            if (user.RoleId == 1)
            {
                List<Genre> genres = context.Genres.ToList();
                ViewData["genres"] = genres;
                List<Boolean> selected = new List<Boolean>();
                for (int i = 1; i <= genres.Count; i++)
                {
                    selected.Add(false);
                }

                Game game = context.Games.Include(g => g.Genres).FirstOrDefault(g => g.GameId == gameId);

                foreach (var g in game.Genres)
                {
                    selected[g.GenreId - 1] = true;
                }
                ViewData["selected"] = selected;

                GameRequirement minimum = context.GameRequirements.FirstOrDefault(gr => gr.GameId == gameId && gr.Type.Equals("minimum"));
                GameRequirement recommend = context.GameRequirements.FirstOrDefault(gr => gr.GameId == gameId && gr.Type.Equals("recommend"));

                ViewData["game"] = game;
                ViewData["minimum"] = minimum;
                ViewData["recommend"] = recommend;
                return Page();
            }

            return Redirect("/Error");
        }

        public async Task<IActionResult> OnPost(IFormFile gameImg, Game game, GameRequirement minimum, GameRequirement recommend, List<int> genres)
        {
            var context = new EvoltingStoreContext();
            List<Genre> allGenres = context.Genres.ToList();

            minimum.Type = "minimum";
            minimum.GameId = game.GameId;

            recommend.Type = "recommend";
            recommend.GameId = game.GameId;

            Game g = context.Games.Include(g => g.Genres).FirstOrDefault(g => g.GameId == game.GameId);

            g.Genres.Clear();

            foreach (var index in genres)
            {
                g.Genres.Add(allGenres[index - 1]);
            }

            context.SaveChanges();

            if (gameImg != null)
            {
                var file = Path.Combine(_environment.ContentRootPath, "uploads", gameImg.FileName);
                using (var fileStream = new FileStream(file, FileMode.Create))
                {
                    await gameImg.CopyToAsync(fileStream);
                }

                DotEnv.Load(options: new DotEnvOptions(probeForEnv: true));
                Cloudinary cloudinary = new Cloudinary(Environment.GetEnvironmentVariable("CLOUDINARY_URL"));
                cloudinary.Api.Secure = true;

                var uploadParams = new ImageUploadParams()
                {
                    File = new FileDescription(Path.Combine(_environment.ContentRootPath, "uploads", gameImg.FileName)),
                    UseFilename = true,
                    UniqueFilename = false,
                    Overwrite = true
                };
                var uploadResult = cloudinary.Upload(uploadParams);
                var myJsonString = uploadResult.JsonObj.ToString();
                var data = JObject.Parse(myJsonString);

                var url = data["url"].ToString();

                game.Image = url;
            }
            else
            {
                game.Image = g.Image;
            }

            game.ReleaseDate = g.ReleaseDate;
            game.UpdateDate = g.UpdateDate;
            game.Genres = g.Genres;

            context = new EvoltingStoreContext();
            context.Entry<Game>(game).State = EntityState.Modified;
            context.SaveChanges();

            GameRequirement m = context.GameRequirements.FirstOrDefault(gr => gr.GameId == game.GameId && gr.Type.Equals("minimum"));
            GameRequirement r = context.GameRequirements.FirstOrDefault(gr => gr.GameId == game.GameId && gr.Type.Equals("recommend"));

            if (m == null)
            {
                context = new EvoltingStoreContext();
                context.GameRequirements.Add(minimum);
                context.SaveChanges();
            }
            else
            {
                context = new EvoltingStoreContext();
                context.Entry<GameRequirement>(minimum).State = EntityState.Modified;
                context.SaveChanges();
            }

            if (r == null)
            {
                context = new EvoltingStoreContext();
                context.GameRequirements.Add(recommend);
                context.SaveChanges();
            }
            else
            {
                context = new EvoltingStoreContext();
                context.Entry<GameRequirement>(recommend).State = EntityState.Modified;
                context.SaveChanges();
            }


            return Redirect("/Management/Games");
        }
    }
}

Pages/Management/Games.cshtml.cs
using EvoltingStore.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EvoltingStore.Pages.Management
{
    public class GamesModel : PageModel
    {
        private EvoltingStoreContext context = new EvoltingStoreContext();

        public IActionResult OnGet()
        {
            String userJSON = (String)HttpContext.Session.GetString("user");
            User user = (User)Newtonsoft.Json.JsonConvert.DeserializeObject<User>(userJSON);
            if (user.RoleId == 1)
            {
                List<Game> games = context.Games.ToList();

                ViewData["games"] = games;

                return Page();
            }

            return Redirect("/Error");
        }

        public IActionResult OnPostRemove(int gameId)
        {
            String userJSON = (String)HttpContext.Session.GetString("user");
            User user = (User)Newtonsoft.Json.JsonConvert.DeserializeObject<User>(userJSON);
            if (user.RoleId == 1)
            {
                Game g = context.Games.FirstOrDefault(g => g.GameId == gameId);

                context.Remove(g);
                context.SaveChanges();

                context = new EvoltingStoreContext();

                List<Game> games = context.Games.ToList();

                ViewData["games"] = games;

                return Page();
            }

            return Redirect("/Error");
        }
    }
}

Pages/Management/UserDetails.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EvoltingStore.Entity;

namespace EvoltingStore.Pages.Management
{
    public class UserDetailsModel : PageModel
    {
        EvoltingStoreContext context = new EvoltingStoreContext();

        public IActionResult OnGet(int userId)
        {
            //var user = (String)HttpContext.Session.GetString("user");
            //var userData = (User)Newtonsoft.Json.JsonConvert.DeserializeObject<User>(user);
            //if (userData.RoleId != 1)
            //{
            //    return;
            //}
            String userJSON = (String)HttpContext.Session.GetString("user");
            User user = (User)Newtonsoft.Json.JsonConvert.DeserializeObject<User>(userJSON);
            if (user.RoleId == 1)
            {
                UserDetail userDetail = context.UserDetails.FirstOrDefault(ud => ud.UserId == userId);

                ViewData["profile"] = userDetail;

                return Page();
            }

            return Redirect("/Error");

        }
    }
}

Pages/Management/Users.cshtml.cs
using EvoltingStore.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace EvoltingStore.Pages.Management
{
    public class UsersModel : PageModel
    {
        private EvoltingStoreContext context = new EvoltingStoreContext();

        public IActionResult OnGet()
        {
            String userJSON = (String)HttpContext.Session.GetString("user");
            User user = (User)Newtonsoft.Json.JsonConvert.DeserializeObject<User>(userJSON);
            if (user.RoleId == 1)
            {
                List<User> users = context.Users.Include(u => u.Role).Include(u => u.UserDetail).ToList();

                ViewData["users"] = users;

                return Page();
            }

            return Redirect("/Error");
        }

        public void OnPostStatus(int userId)
        {
            User user = context.Users.FirstOrDefault(u => u.UserId == userId);
            user.IsActive = !user.IsActive;

            context.SaveChanges();

            List<User> users = context.Users.Include(u => u.Role).Include(u => u.UserDetail).ToList();

            ViewData["users"] = users;
        }
    }
}

Pages/Management/DeleteGame.cshtml
@page
@model EvoltingStore.Pages.Management.DeleteGameModel
@{
}

Pages/Management/Games.cshtml
@page
@model EvoltingStore.Pages.Management.GamesModel
@using EvoltingStore.Entity
@{
    Layout = "Shared/_Layout";
    ViewData["Title"] = "Games Management";

    var user = (String)HttpContext.Session.GetString("user");
    var userData = (User)Newtonsoft.Json.JsonConvert.DeserializeObject<User>(user);
}

@{
    var games = (List<Game>)ViewData["games"];
}

<!-- Page Preloder -->
<div id="preloder">
    <div class="loader"></div>
</div>

<!-- Header Section Begin -->
<header class="header">
    <div class="container">
        <div class="row">
            <div class="col-lg-2">
                <div class="header__logo">
                    <a href="/Index">
                        <img src="img/logo.png" alt="">
                    </a>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="header__nav">
                    <nav class="header__menu mobile-menu">
                        <ul>
                            <li><a href="/Index">Homepage</a></li>
                            <li><a href="/Categories">Browse</a></li>
                            <li><a href="#">Our Blog</a></li>
                            <li><a href="#">Contacts</a></li>
                            @if (userData != null)
                            {
                                    <li><a href="#">My Favourite</a></li>
                            }
                        </ul>
                    </nav>
                </div>
            </div>
            <div class="col-lg-2">
                <div class="header__right">
                    <a href="#" class="search-switch"><span class="icon_search"></span></a>
                    @if (user != null)
                    {
                            <a href="/Profile"><span class="icon_profile"></span></a>
                    }
                    else
                    {
                            <a href="/Login">Login Now</a>
                    }
                </div>
            </div>
        </div>
        <div id="mobile-menu-wrap"></div>
    </div>
</header>
<!-- Header End -->

<div class="container-xl">
    <div class="table-responsive">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-5">
                        <h2>Game <b>Management</b></h2>
                    </div>
                    <div class="col-sm-7">
                        <a href="/Management/AddGame" ><button class="btn btn-secondary">Add New Game</button></a>					
                    </div>
                </div>
            </div>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>	
                        <th>Released Dated</th>
                        <th>Update Dated</th>
                        <th>Platform</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var g in games)
                    {
                            <tr>
                                <form method="post" asp-page-handler="Remove">
                                    <input type="text" name="userId" value="@g.GameId" hidden/>
                                    <td>@g.GameId</td>
                                    <td> 
                                        <a href="/Management/EditGame?gameId=@g.GameId"><img src="@g.Image" style="width: 50px; height: 50px" class="avatar" alt="Avatar"/> @g.Name</a>
                                    </td>
                                    <td>@g.ReleaseDate.ToShortDateString()</td>                        
                                    <td>@g.UpdateDate.ToShortDateString()</td>
                                    <td><span class="status text-success"></span>@g.Platform</td>
                                    <td>
                                        <input type="submit" value="Remove" class="btn btn-danger"/>
                                    </td>
                                </form>
                            </tr>
                    }                    
                </tbody>
            </table>
        </div>
    </div>
</div>



<style>
    body {
        color: #566787;
        background: #f5f5f5;
        font-family: 'Varela Round', sans-serif;
        font-size: 13px;
    }
    .table-responsive {
        margin: 30px 0;
    }
    .table-wrapper {
        min-width: 1000px;
        background: #fff;
        padding: 20px 25px;
        border-radius: 3px;
        box-shadow: 0 1px 1px rgba(0,0,0,.05);
    }
    .table-title {
        padding-bottom: 15px;
        background: #299be4;
        color: #fff;
        padding: 16px 30px;
        margin: -20px -25px 10px;
        border-radius: 3px 3px 0 0;
    }
    .table-title h2 {
        margin: 5px 0 0;
        font-size: 24px;
    }
    .table-title .btn {
        color: #566787;
        float: right;
        font-size: 13px;
        background: #fff;
        border: none;
        min-width: 50px;
        border-radius: 2px;
        border: none;
        outline: none !important;
        margin-left: 10px;
    }
    .table-title .btn:hover, .table-title .btn:focus {
        color: #566787;
        background: #f2f2f2;
    }
    .table-title .btn i {
        float: left;
        font-size: 21px;
        margin-right: 5px;
    }
    .table-title .btn span {
        float: left;
        margin-top: 2px;
    }
    table.table tr th, table.table tr td {
        border-color: #e9e9e9;
        padding: 12px 15px;
        vertical-align: middle;
    }
    table.table tr th:first-child {
        width: 60px;
    }
    table.table tr th:last-child {
        width: 100px;
    }
    table.table-striped tbody tr:nth-of-type(odd) {
        background-color: #fcfcfc;
    }
    table.table-striped.table-hover tbody tr:hover {
        background: #f5f5f5;
    }
    table.table th i {
        font-size: 13px;
        margin: 0 5px;
        cursor: pointer;
    }	
    table.table td:last-child i {
        opacity: 0.9;
        font-size: 22px;
        margin: 0 5px;
    }
    table.table td a {
        font-weight: bold;
        color: #566787;
        display: inline-block;
        text-decoration: none;
    }
    table.table td a:hover {
        color: #2196F3;
    }
    table.table td a.settings {
        color: #2196F3;
    }
    table.table td a.delete {
        color: #F44336;
    }
    table.table td i {
        font-size: 19px;
    }
    table.table .avatar {
        border-radius: 50%;
        vertical-align: middle;
        margin-right: 10px;
    }
    .status {
        font-size: 30px;
        margin: 2px 2px 0 0;
        display: inline-block;
        vertical-align: middle;
        line-height: 10px;
    }
    .text-success {
        color: #10c469;
    }
    .text-info {
        color: #62c9e8;
    }
    .text-warning {
        color: #FFC107;
    }
    .text-danger {
        color: #ff5b5b;
    }
    .pagination {
        float: right;
        margin: 0 0 5px;
    }
    .pagination li a {
        border: none;
        font-size: 13px;
        min-width: 30px;
        min-height: 30px;
        color: #999;
        margin: 0 2px;
        line-height: 30px;
        border-radius: 2px !important;
        text-align: center;
        padding: 0 6px;
    }
    .pagination li a:hover {
        color: #666;
    }	
    .pagination li.active a, .pagination li.active a.page-link {
        background: #03A9F4;
    }
    .pagination li.active a:hover {        
        background: #0397d6;
    }
    .pagination li.disabled i {
        color: #ccc;
    }
    .pagination li i {
        font-size: 16px;
        padding-top: 6px
    }
    .hint-text {
        float: left;
        margin-top: 10px;
        font-size: 13px;
    }
</style>
<script>
    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>

Pages/Management/Users.cshtml
@page
@model EvoltingStore.Pages.Management.UsersModel
@using EvoltingStore.Entity
@addTagHelper *, EvoltingStore

@{
    Layout = "_Layout";
    ViewData["Title"] = "Users Management";
}

@{
    var users = (List<User>)ViewData["users"];

    var user = (String)HttpContext.Session.GetString("user");
    var userData = (User)Newtonsoft.Json.JsonConvert.DeserializeObject<User>(user);
}

<!-- Page Preloder -->
<div id="preloder">
    <div class="loader"></div>
</div>

<!-- Header Section Begin -->
<header class="header">
    <div class="container">
        <div class="row">
            <div class="col-lg-2">
                <div class="header__logo">
                    <a href="/Index">
                        <img src="img/logo.png" alt="">
                    </a>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="header__nav">
                    <nav class="header__menu mobile-menu">
                        <ul>
                            <li><a href="/Index">Homepage</a></li>
                            <li><a href="/Categories">Browse</a></li>
                            <li><a href="#">Our Blog</a></li>
                            <li><a href="#">Contacts</a></li>
                            @if (userData != null)
                            {
                                <li><a href="#">My Favourite</a></li>
                            }
                        </ul>
                    </nav>
                </div>
            </div>
            <div class="col-lg-2">
                <div class="header__right">
                    <a href="#" class="search-switch"><span class="icon_search"></span></a>
                    @if (user != null)
                    {
                                <a href="/Profile"><span class="icon_profile"></span></a>
                    }
                    else
                    {
                                <a href="/Login">Login Now</a>
                    }
                </div>
            </div>
        </div>
        <div id="mobile-menu-wrap"></div>
    </div>
</header>
<!-- Header End -->

<div class="container-xl">
    <div class="table-responsive">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-5">
                        <h2>User <b>Management</b></h2>
                    </div>
                </div>
            </div>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>						
                        <th>Date Created</th>
                        <th>Role</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(var u in users){
                        <tr>
                            <form method="post" asp-page-handler="Status">
                                <input type="text" name="userId" value="@u.UserId" hidden/>
                                <td>@u.UserId</td>
                                <td>
                                    @if (u.UserId == userData.UserId)
                                    {
                                        <a href="/Profile">@u.Username</a>
                                    }
                                    else
                                    {
                                        <a href="/Management/UserDetails?userId=@u.UserId">@u.Username</a>
                                    }
                                    
                                </td>
                                <td>@u.UserDetail.CreatedDate.ToShortDateString()</td>                        
                                <td>@u.Role.RoleName</td>
                                @if (u.IsActive)
                                {
                                        <td><span class="status text-success">&bull;</span> Active</td>
                                }
                                else
                                {
                                        <td><span class="status text-danger">&bull;</span> Suspended</td> 
                                }
                                <td>
                                    @if (u.UserId == userData.UserId){
                                        <input type="submit" value="Deactivate" class="btn btn-danger" disabled/>
                                    }
                                    else{
                                        @if (u.IsActive)
                                        {
                                            <input type="submit" value="Deactivate" class="btn btn-danger"/>
                                        }
                                        else
                                        {
                                            <input type="submit" value="Activate" class="btn btn-success"/>
                                        }
                                    }
                                </td>
                            </form>
                        </tr>
                    }                    
                </tbody>
            </table>
        </div>
    </div>
</div>



<style>
    body {
        color: #566787;
        background: #f5f5f5;
        font-family: 'Varela Round', sans-serif;
        font-size: 13px;
    }
    .table-responsive {
        margin: 30px 0;
    }
    .table-wrapper {
        min-width: 1000px;
        background: #fff;
        padding: 20px 25px;
        border-radius: 3px;
        box-shadow: 0 1px 1px rgba(0,0,0,.05);
    }
    .table-title {
        padding-bottom: 15px;
        background: #299be4;
        color: #fff;
        padding: 16px 30px;
        margin: -20px -25px 10px;
        border-radius: 3px 3px 0 0;
    }
    .table-title h2 {
        margin: 5px 0 0;
        font-size: 24px;
    }
    .table-title .btn {
        color: #566787;
        float: right;
        font-size: 13px;
        background: #fff;
        border: none;
        min-width: 50px;
        border-radius: 2px;
        border: none;
        outline: none !important;
        margin-left: 10px;
    }
    .table-title .btn:hover, .table-title .btn:focus {
        color: #566787;
        background: #f2f2f2;
    }
    .table-title .btn i {
        float: left;
        font-size: 21px;
        margin-right: 5px;
    }
    .table-title .btn span {
        float: left;
        margin-top: 2px;
    }
    table.table tr th, table.table tr td {
        border-color: #e9e9e9;
        padding: 12px 15px;
        vertical-align: middle;
    }
    table.table tr th:first-child {
        width: 60px;
    }
    table.table tr th:last-child {
        width: 100px;
    }
    table.table-striped tbody tr:nth-of-type(odd) {
        background-color: #fcfcfc;
    }
    table.table-striped.table-hover tbody tr:hover {
        background: #f5f5f5;
    }
    table.table th i {
        font-size: 13px;
        margin: 0 5px;
        cursor: pointer;
    }	
    table.table td:last-child i {
        opacity: 0.9;
        font-size: 22px;
        margin: 0 5px;
    }
    table.table td a {
        font-weight: bold;
        color: #566787;
        display: inline-block;
        text-decoration: none;
    }
    table.table td a:hover {
        color: #2196F3;
    }
    table.table td a.settings {
        color: #2196F3;
    }
    table.table td a.delete {
        color: #F44336;
    }
    table.table td i {
        font-size: 19px;
    }
    table.table .avatar {
        border-radius: 50%;
        vertical-align: middle;
        margin-right: 10px;
    }
    .status {
        font-size: 30px;
        margin: 2px 2px 0 0;
        display: inline-block;
        vertical-align: middle;
        line-height: 10px;
    }
    .text-success {
        color: #10c469;
    }
    .text-info {
        color: #62c9e8;
    }
    .text-warning {
        color: #FFC107;
    }
    .text-danger {
        color: #ff5b5b;
    }
    .pagination {
        float: right;
        margin: 0 0 5px;
    }
    .pagination li a {
        border: none;
        font-size: 13px;
        min-width: 30px;
        min-height: 30px;
        color: #999;
        margin: 0 2px;
        line-height: 30px;
        border-radius: 2px !important;
        text-align: center;
        padding: 0 6px;
    }
    .pagination li a:hover {
        color: #666;
    }	
    .pagination li.active a, .pagination li.active a.page-link {
        background: #03A9F4;
    }
    .pagination li.active a:hover {        
        background: #0397d6;
    }
    .pagination li.disabled i {
        color: #ccc;
    }
    .pagination li i {
        font-size: 16px;
        padding-top: 6px
    }
    .hint-text {
        float: left;
        margin-top: 10px;
        font-size: 13px;
    }
</style>
<script>
    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>