Pages/Blog.cshtml.cs
using EvoltingStore.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace EvoltingStore.Pages
{
    public class BlogModel : PageModel
    {
        public async Task OnGetAsync()
        {
            var client = new HttpClient();
            var request = new HttpRequestMessage
            {
                Method = HttpMethod.Get,
                RequestUri = new Uri("https://videogames-news2.p.rapidapi.com/videogames_news/search_news?query=game"),
                Headers =
                {
                    { "X-RapidAPI-Key", "a183a6bf1cmshc0ecd4f7ec60cdep1ecbc5jsn50d81c06026d" },
                    { "X-RapidAPI-Host", "videogames-news2.p.rapidapi.com" },
                },
            };
            using (var response = await client.SendAsync(request))
            {
                response.EnsureSuccessStatusCode();
                var body = await response.Content.ReadAsStringAsync();
                
                List<News> news = JsonConvert.DeserializeObject<List<News>>(body);

                ViewData["news"] = news;
            }
        }

        public async Task OnPostAsync(String query)
        {
            var client = new HttpClient();
            var request = new HttpRequestMessage
            {
                Method = HttpMethod.Get,
                RequestUri = new Uri("https://videogames-news2.p.rapidapi.com/videogames_news/search_news?query="+query),
                Headers =
                {
                    { "X-RapidAPI-Key", "a183a6bf1cmshc0ecd4f7ec60cdep1ecbc5jsn50d81c06026d" },
                    { "X-RapidAPI-Host", "videogames-news2.p.rapidapi.com" },
                },
            };
            using (var response = await client.SendAsync(request))
            {
                response.EnsureSuccessStatusCode();
                var body = await response.Content.ReadAsStringAsync();

                List<News> news = JsonConvert.DeserializeObject<List<News>>(body);

                ViewData["news"] = news;
            }
        }
    }
}

Pages/Categories.cshtml.cs
using EvoltingStore.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace EvoltingStore.Pages
{
    public class CategoriesModel : PageModel
    {
        private EvoltingStoreContext context = new EvoltingStoreContext();

        public void OnGet(String orderBy)
        {
            List<Game> games = context.Games.Include(g => g.Genres).Include(g => g.Comments).Include(g => g.Users).OrderBy(g => g.Name).ToList();
            List<Genre> genres = context.Genres.ToList();
            List<Boolean> selected = new List<Boolean>();
            for (int i = 1; i <= genres.Count; i++)
            {
                selected.Add(false);
            }

            if (orderBy != null && orderBy.Length > 0)
            {
                switch (orderBy)
                {
                    case "Name":
                        games = games.OrderByDescending(g => g.Name).ToList();
                        break;
                    case "UpdateDate":
                        games = games.OrderByDescending(g => g.UpdateDate).ToList();
                        break;
                    case "ReleaseDate":
                        games = games.OrderByDescending(g => g.ReleaseDate).ToList();
                        break;
                    case "Favourites":
                        games = games.OrderByDescending(g => g.Users.Count).ToList();
                        break;
                }

                ViewData["orderBy"] = orderBy;
            }


            ViewData["games"] = games;
            ViewData["genres"] = genres;
            ViewData["selected"] = selected;
        }

        public void OnPostFilter(List<int> genre, string searchName, string orderBy)
        {
            List<Game> games = new List<Game>();
            List<Boolean> selected = new List<Boolean>();
            List<Genre> genres = context.Genres.ToList();

            if (genre.Count > 0)
            {
                List<Genre> selectedGenre = new List<Genre>();

                foreach (var genreId in genre)
                {
                    selectedGenre.Add(genres[genreId - 1]);
                }

                foreach (var game in context.Games.Include(g => g.Genres).Include(g => g.Comments).Include(g => g.Users).ToList())
                {
                    HashSet<Genre> common = new HashSet<Genre>(game.Genres);
                    common.IntersectWith(selectedGenre);
                    if (common.Count == selectedGenre.Count)
                    {
                        games.Add(game);
                    }
                }

                for (int i = 1; i <= genres.Count; i++)
                {
                    if (genre.Contains(i)) selected.Add(true);
                    else selected.Add(false);
                }
            }
            else
            {
                games = context.Games.Include(g => g.Genres).Include(g => g.Comments).Include(g => g.Users).ToList();

                for (int i = 1; i <= genres.Count; i++)
                {
                    selected.Add(false);
                }
            }

            if(searchName != null && searchName.Length > 0)
            {
                games = (from g in games
                         where g.Name.Contains(searchName)
                         select g).ToList();
            }

            switch (orderBy)
            {
                case "Name":
                    games = games.OrderByDescending(g => g.Name).ToList();
                    break;
                case "UpdateDate":
                    games = games.OrderByDescending(g => g.UpdateDate).ToList();
                    break;
                case "ReleaseDate":
                    games = games.OrderByDescending(g => g.ReleaseDate).ToList();
                    break;
                case "Favourites":
                    games = games.OrderByDescending(g => g.Users.Count).ToList();
                    break;
            }

            ViewData["games"] = games;
            ViewData["genres"] = genres;
            ViewData["selected"] = selected;

            ViewData["orderBy"] = orderBy;
            ViewData["searchName"] = searchName;
        }
    }
}

Pages/Detail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EvoltingStore.Pages
{
    public class DetailModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Details.cshtml.cs
using EvoltingStore.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace EvoltingStore.Pages
{
    public class DetailsModel : PageModel
    {
        EvoltingStoreContext context = new EvoltingStoreContext();

        public async Task OnGetAsync(int gameId)
        {
            Game game = context.Games.Include(g => g.Genres).Include(g => g.Comments).ThenInclude(c => c.User).Include(g => g.Users).FirstOrDefault(g => g.GameId == gameId);
            Boolean isFavourite = false;
            
            String userJSON = HttpContext.Session.GetString("user");
            if(userJSON != null)
            {
                User us = Newtonsoft.Json.JsonConvert.DeserializeObject<User>(userJSON);

                User user = context.Users.FirstOrDefault(u => u.UserId == us.UserId);


                if (game.Users.Contains(user))
                {
                    isFavourite = true;
                }
            }


            GameRequirement minimum = context.GameRequirements.FirstOrDefault(gr => gr.GameId == gameId && gr.Type.Equals("minimum"));
            GameRequirement recommend = context.GameRequirements.FirstOrDefault(gr => gr.GameId == gameId && gr.Type.Equals("recommend"));

           

            ViewData["isFavourite"] = isFavourite;
            ViewData["game"] = game;
            ViewData["minimum"] = minimum;
            ViewData["recommend"] = recommend;

            var client = new HttpClient();
            var request = new HttpRequestMessage
            {
                Method = HttpMethod.Get,
                RequestUri = new Uri("https://videogames-news2.p.rapidapi.com/videogames_news/search_news?query=" + game.Name),
                Headers =
                {
                    { "X-RapidAPI-Key", "a183a6bf1cmshc0ecd4f7ec60cdep1ecbc5jsn50d81c06026d" },
                    { "X-RapidAPI-Host", "videogames-news2.p.rapidapi.com" },
                },
            };
            using (var response = await client.SendAsync(request))
            {
                response.EnsureSuccessStatusCode();
                var body = await response.Content.ReadAsStringAsync();

                List<News> news = JsonConvert.DeserializeObject<List<News>>(body);

                ViewData["news"] = news;
            }
        }

        public async Task OnPostFavouriteAsync(int gameId)
        {
            Game game = context.Games.Include(g => g.Genres).Include(g => g.Comments).ThenInclude(c => c.User).Include(g => g.Users).FirstOrDefault(g => g.GameId == gameId);
            Boolean isFavourite = false;

            String userJSON = HttpContext.Session.GetString("user");
            if(userJSON != null)
            {
                User us = Newtonsoft.Json.JsonConvert.DeserializeObject<User>(userJSON);

                User user = context.Users.FirstOrDefault(u => u.UserId == us.UserId);


                if (game.Users.Contains(user))
                {
                    game.Users.Remove(user);
                }
                else
                {
                    game.Users.Add(user);
                    isFavourite = true;
                }
            }

            context.Games.Update(game);
            context.SaveChanges();


            GameRequirement minimum = context.GameRequirements.FirstOrDefault(gr => gr.GameId == gameId && gr.Type.Equals("minimum"));
            GameRequirement recommend = context.GameRequirements.FirstOrDefault(gr => gr.GameId == gameId && gr.Type.Equals("recommend"));

            ViewData["isFavourite"] = isFavourite;
            ViewData["game"] = game;
            ViewData["minimum"] = minimum;
            ViewData["recommend"] = recommend;

            var client = new HttpClient();
            var request = new HttpRequestMessage
            {
                Method = HttpMethod.Get,
                RequestUri = new Uri("https://videogames-news2.p.rapidapi.com/videogames_news/search_news?query=" + game.Name),
                Headers =
                {
                    { "X-RapidAPI-Key", "a183a6bf1cmshc0ecd4f7ec60cdep1ecbc5jsn50d81c06026d" },
                    { "X-RapidAPI-Host", "videogames-news2.p.rapidapi.com" },
                },
            };
            using (var response = await client.SendAsync(request))
            {
                response.EnsureSuccessStatusCode();
                var body = await response.Content.ReadAsStringAsync();

                List<News> news = JsonConvert.DeserializeObject<List<News>>(body);

                ViewData["news"] = news;
            }
        }

        public void OnPostComment(int gameId, string messageInput)
        {
            Comment c = new Comment();
            Game game = context.Games.Include(g => g.Genres).Include(g => g.Comments).ThenInclude(c => c.User).Include(g => g.Users).FirstOrDefault(g => g.GameId == gameId);
            Boolean isFavourite = false;

            String userJSON = HttpContext.Session.GetString("user");
            
            if(userJSON != null)
            {
                User us = Newtonsoft.Json.JsonConvert.DeserializeObject<User>(userJSON);

                c.UserId = us.UserId;
                c.GameId = gameId;
                c.Content = messageInput;
                c.PostTime = DateTime.Now;

                context.Comments.Add(c);

                User user = context.Users.FirstOrDefault(u => u.UserId == us.UserId);


                if (game.Users.Contains(user))
                {
                    isFavourite = true;
                }

                context.Games.Update(game);
                context.SaveChanges();
            }


            GameRequirement minimum = context.GameRequirements.FirstOrDefault(gr => gr.GameId == gameId && gr.Type.Equals("minimum"));
            GameRequirement recommend = context.GameRequirements.FirstOrDefault(gr => gr.GameId == gameId && gr.Type.Equals("recommend"));

            ViewData["isFavourite"] = isFavourite;
            ViewData["game"] = game;
            ViewData["minimum"] = minimum;
            ViewData["recommend"] = recommend;
        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace EvoltingStore.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using EvoltingStore.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace EvoltingStore.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        private EvoltingStoreContext context = new EvoltingStoreContext();

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            List<Game> topFavourites = context.Games.Include(g => g.Genres).Include(g => g.Comments).Include(g => g.Users).OrderByDescending(g => g.Users.Count).Take(6).ToList();
            List<Game> latestRelease = context.Games.Include(g => g.Genres).Include(g => g.Comments).Include(g => g.Users).OrderByDescending(g => g.ReleaseDate).Take(6).ToList();
            List<Game> latestUpdate = context.Games.Include(g => g.Genres).Include(g => g.Comments).Include(g => g.Users).OrderByDescending(g => g.UpdateDate).Take(6).ToList();
            List<Comment> comments = context.Comments.OrderByDescending(c => c.PostTime).ToList();

            List<Game> latestCommment = comments.Select(c => c.Game).ToList();
            latestCommment = latestCommment.GroupBy(g => g.GameId).Select(g => g.First()).Take(6).ToList();

            ViewData["topFavourites"] = topFavourites;
            ViewData["latestRelease"] = latestRelease;
            ViewData["latestUpdate"] = latestUpdate;
            ViewData["latestCommment"] = latestCommment;
            String jsonUser = HttpContext.Session.GetString("user");
            User user = null;
            if (jsonUser != null)
            {
                user = Newtonsoft.Json.JsonConvert.DeserializeObject<User>(jsonUser);
            }

            ViewData["user"] = user;
        }
    }
}

Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EvoltingStore.Pages
{
    public class LogoutModel : PageModel
    {
        public IActionResult OnGet()
        {
            HttpContext.Session.Remove("user");
            HttpContext.Session.Remove("userDetail");

            return Redirect("/Index");
        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EvoltingStore.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Profile.cshtml.cs
using EvoltingStore.Entity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EvoltingStore.Pages
{
    public class ProfileModel : PageModel
    {
        private EvoltingStoreContext context = new EvoltingStoreContext();

        public void OnGet()
        {
        }

        public void OnPostPassword(String username, String password)
        {
            User user = context.Users.First(u => u.Username == username);
            if (user != null)
            {
                user.Password = password;

                context.SaveChanges();
            }

            String jsonUser = Newtonsoft.Json.JsonConvert.SerializeObject(user);
            HttpContext.Session.SetString("user", jsonUser);
        }

        public void OnPostDetail(int userId, String firstName, String lastName, String email)
        {
            UserDetail userDetail = context.UserDetails.First(u => u.UserId == userId);
            if (userDetail != null)
            {
                userDetail.FirstName = firstName;
                userDetail.LastName = lastName;
                userDetail.Email = email;

                context.SaveChanges();

                String jsonUserDetail = Newtonsoft.Json.JsonConvert.SerializeObject(userDetail);
                HttpContext.Session.SetString("userDetail", jsonUserDetail);
            }
        }
    }
}

Pages/Blog.cshtml
@page
@model EvoltingStore.Pages.BlogModel
@using EvoltingStore.Entity

@{
    Layout = "_Layout";
    ViewData["Title"] = "Blog";
}

@{
    var news = (List<News>)ViewData["news"];

    var user = HttpContext.Session.GetString("user");
    var userData = ViewData["userDetail"];
    if (user != null)
    {
        userData = (User)Newtonsoft.Json.JsonConvert.DeserializeObject<User>(user);
    }
}

<!-- Page Preloder -->
<div id="preloder">
    <div class="loader"></div>
</div>

<!-- Header Section Begin -->
<header class="header">
    <div class="container">
        <div class="row">
            <div class="col-lg-2">
                <div class="header__logo">
                    <a href="/Index">
                        <img src="img/logo.png" alt="">
                    </a>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="header__nav">
                    <nav class="header__menu mobile-menu">
                        <ul>
                            <li><a href="/Index">Homepage</a></li>
                            <li><a href="/Categories">Browse</a></li>
                            <li class="active"><a href="/Blog">Our Blog</a></li>
                            <li><a href="#">Contacts</a></li>
                            @if (userData != null)
                            {
                                    <li><a href="#">My Favourite</a></li>
                            }
                        </ul>
                    </nav>
                </div>
            </div>
            <div class="col-lg-2">
                <div class="header__right">
                        <a href="#" class="search-switch"><span class="icon_search"></span></a>
                    @if (user != null)
                    {
                                    <a href="/Profile"><span class="icon_profile"></span></a>
                    }
                    else
                    {
                                    <a href="/Login">Login Now</a>
                    }
                    </div>
            </div>
        </div>
        <div id="mobile-menu-wrap"></div>
    </div>
</header>
<!-- Header End -->

<!-- Product Section Begin -->
<section class="product-page spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-10">
                <div class="product__page__content">
                    <div class="row">
                        @foreach (var n in news)
                        {
                            <div class="col-lg-6 col-md-12">
                                <div class="product__item">
                                        <div class="product__item__pic set-bg" data-setbg="@n.Image">
                                        <div class="ep">@n.Date</div>
                                    </div>
                                    <div class="product__item__text">
                                        <h5><a href="@n.Link">@n.Title</a></h5>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 col-sm-6">
                <div class="product__sidebar">
                    <div class="product__sidebar__view">
                        <div class="section-title">
                            <h5>Search for News</h5>
                        </div>
                        <div class="filter__gallery">
                            <div class="filter-container">
                                <form method="post">
                                    <div class="form-group m-2">
                                        <label for="searchName"><h3 style="color: papayawhip">Search</h3></label>
                                        <div>
                                            <input type="text" name="query" placeholder="Game Name"/>
                                        </div>
                                    </div>
                                    <input class="btn btn-primary m-2" type="submit" value="Filter" />
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Product Section End -->

<!-- Footer Section Begin -->
<footer class="footer">
    <div class="page-up">
        <a href="#" id="scrollToTopButton"><span class="arrow_carrot-up"></span></a>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="footer__logo">
                    <a href="./index.html"><img src="img/logo.png" alt=""></a>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="footer__nav">
                    <ul>
                        <li><a href="/Index">Homepage</a></li>
                        <li><a href="/Categories">Browse</a></li>
                        <li><a href="#">Our Blog</a></li>
                        <li><a href="#">Contacts</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3">
                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>

                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

    <!-- Search model Begin -->
    <div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch"><i class="icon_close"></i></div>
        <form class="search-model-form">
            <input type="text" id="search-input" placeholder="Search here.....">
        </form>
    </div>
</div>
<!-- Search model end -->

Pages/Logout.cshtml
@page
@model EvoltingStore.Pages.LogoutModel
@{
}

Pages/Profile.cshtml
@page
@model EvoltingStore.Pages.ProfileModel
@using EvoltingStore.Entity
@{
    Layout = "_Layout";
    ViewData["Title"] = "Your Profile";
}

@{
    var user = (String)HttpContext.Session.GetString("user");
    var userDetail = (String)HttpContext.Session.GetString("userDetail");

    var userData = (User)Newtonsoft.Json.JsonConvert.DeserializeObject<User>(user);
    var userDetailData = (UserDetail)Newtonsoft.Json.JsonConvert.DeserializeObject<UserDetail>(userDetail);
}

<!-- Page Preloder -->
<div id="preloder">
    <div class="loader"></div>
</div>

<!-- Header Section Begin -->
<header class="header">
    <div class="container">
        <div class="row">
            <div class="col-lg-2">
                <div class="header__logo">
                    <a href="/Index">
                        <img src="img/logo.png" alt="">
                    </a>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="header__nav">
                    <nav class="header__menu mobile-menu">
                        <ul>
                            <li><a href="/Index">Homepage</a></li>
                            <li><a href="/Categories">Browse</a></li>
                            <li><a href="/Blog">Our Blog</a></li>
                            <li><a href="#">Contacts</a></li>
                            @if (userData != null)
                            {
                                <li><a href="#">My Favourite</a></li>
                            }
                        </ul>
                    </nav>
                </div>
            </div>
            <div class="col-lg-2">
                <div class="header__right">
                    <a href="#" class="search-switch"><span class="icon_search"></span></a>
                    @if (user != null)
                    {
                        <a href="/Profile"><span class="icon_profile"></span></a>
                    }
                    else
                    {
                        <a href="/Login">Login Now</a>
                    }
                </div>
            </div>
        </div>
        <div id="mobile-menu-wrap"></div>
    </div>
</header>
<!-- Header End -->

<div class="container rounded bg-white mt-5 mb-5"> 
    <div class="row"> 
        <div class="col-md-3 border-right"> 
            <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                <img class="rounded-circle mt-5" src="http://cdn.onlinewebfonts.com/svg/img_264570.png">
                <span class="font-weight-bold">@userData.Username</span>
                <span class="text-black-50">@userDetailData.Email</span>
                <span> </span>
                <a href="/Logout"><button class="btn btn-danger m-3">Log Out</button></a>
            </div> 
        </div> 
        <div class="col-md-5 border-right"> 
            <div class="p-3 py-5"> 
                <form method="post" asp-page-handler="Detail">
                    <div class="d-flex justify-content-between align-items-center mb-3"> 
                        <h4 class="text-right">Profile Settings</h4> 
                        <input type="text" name="userId" class="form-control" value="@userDetailData.UserId" hidden>
                    </div> 
                    <div class="row mt-2"> 
                        <div class="col-md-6">
                            <label class="labels">First Name</label>
                            <input type="text" name="firstName" class="form-control" placeholder="first name" value="@userDetailData.FirstName">
                        </div> 
                        <div class="col-md-6">
                            <label class="labels">Last Name</label>
                            <input type="text" name="lastName" class="form-control" placeholder="last name" value="@userDetailData.LastName">
                        </div> 
                    </div> 
                    <div class="row mt-3"> 
                        <div class="col-md-12">
                            <label class="labels">Email</label>
                            <input type="text" name="email" class="form-control" placeholder="enter email id" value="@userDetailData.Email">
                        </div> 
                        <div class="col-md-12">
                            <label class="labels">Created Date</label>
                            <input type="text" class="form-control" value="@userDetailData.CreatedDate.ToShortDateString()" readonly>
                        </div> 
                    </div> 
                    <div class="mt-5 text-center">
                        <input class="btn btn-primary profile-button" type="submit" value="Save Profile"/>
                    </div>
                </form>
            </div> 
        </div> 
        <div class="col-md-4"> 
            <div class="p-3 py-5"> 
                <form id="changePassForm" onsubmit="return reconfirm()" method="post" asp-page-handler="Password">
                    <div class="d-flex justify-content-between align-items-center experience">
                        <span>Change Password</span>
                    </div><br> 
                    <div class="col-md-12">
                        <label class="labels">Username</label>
                        <input type="text" class="form-control" name="username" value="@userData.Username" readonly>
                    </div> <br> 
                    <div class="col-md-12">
                        <label class="labels">New Password</label>
                        <input type="text" class="form-control"name="password" placeholder="New Password" value="">
                    </div>
                    <div class="d-flex justify-content-between align-items-center experience">
                        <input type="submit" class="btn btn-success m-3" value="Change Password"/>
                    </div><br>. 
                </form>
            </div> 
            @if(userData.RoleId == 1){
                <div class="p-3 py-5"> 
                    <div class="d-flex justify-content-between align-items-center experience">
                        <span>Admin Privileges</span>
                    </div><br> 
                    <div class="col-md-12">
                            <a href="/Management/Users"><button class="btn btn-warning mb-1">User Management</button></a>
                    </div> 
                    <div class="col-md-12">
                            <a href="/Management/Games"><button class="btn btn-dark mt-1">Game Management</button></a>
                    </div>
                </div> 
            }
        </div> 
    </div>
</div>

<script type="text/javascript">
    function reconfirm() {
      let password = prompt("Please enter your old password");
      if (password == @userData.Password) {
        return true;
      }
      else{
        alert("Wrong password. Change will not be saved")
        return false;
      }
    }
</script>